openapi: 3.0.0
info:
  title: Admin Panel API
  version: 1.0.0
  description: API documentation for SmartCard endpoints
components:
  schemas:
    SmartCard:
      type: object
      properties:
        name:
          type: string
        minVisits:
          type: integer
        discount:
          type: number
        type:
          type: string
          enum: [Silver, Gold, Platinum, Diamond, VIP]
        validity:
          type: integer
        description:
          type: string
paths:
  /api/v1/smartcard/get:
    get:
      summary: Get Smart Card
      tags: [SmartCard]
      responses:
        '200':
          description: SSmart Card
  /api/v1/smartcard/add:
    post:
      summary: Add Smart Card
      tags: [SmartCard]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SmartCard'
      responses:
        '201':
          description: Smart card successfully added
